name: fr3sim

channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy
  - pinocchio=3.9
  - pybind11
  - cmake
  - pkg-config
  - cxx-compiler
  - make
  - eigen
  - urdfdom
  - console_bridge
  - tinyxml2
  - pip
  - setuptools
  - wheel
